coverage:
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 0%
    patch:
      default:
        enabled: yes
        target: auto
        threshold: 0%
